<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Deceased</name>
   <tag></tag>
   <elementGuidId>37e8a907-d668-4617-aac4-c3b06069d58d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='ngFormIndividual']/fieldset/div[4]/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9307930-8603-41cc-bffa-e12a92d33d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio-container</value>
      <webElementGuid>5b80212e-c5cf-4f36-b44f-95a6becd3eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deceased</value>
      <webElementGuid>d540a78b-f23e-4530-8d1e-de84be743845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngFormIndividual&quot;)/fieldset[1]/div[@class=&quot;ft-form-row col1-v100&quot;]/div[1]/div[@class=&quot;ft-form-input&quot;]/div[1]/div[@class=&quot;input-radio-container&quot;]</value>
      <webElementGuid>76882b1a-a448-43bb-9681-d98695a3e9ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ngFormIndividual']/fieldset/div[4]/div/div/div/div[2]</value>
      <webElementGuid>fe9efeb3-2b30-4175-8096-bd5dc0927338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I live'])[1]/following::div[1]</value>
      <webElementGuid>981f0fb5-ecae-46fe-9f0b-85978e44e276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Birthplace'])[1]/following::div[7]</value>
      <webElementGuid>b0fba39f-2841-42bc-bd4f-7a452208eb88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unknown'])[2]/preceding::div[1]</value>
      <webElementGuid>6a5c6f99-520a-41e2-9bd6-6d11a5afa283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]</value>
      <webElementGuid>454e4809-0dd3-444f-be1b-1c8fa4b2ae4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Deceased' or . = 'Deceased')]</value>
      <webElementGuid>56ebcc68-3b4b-4a19-8a09-d0033fa3ca29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
