<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Birthplace_ng-untouched ng-pristine ng-valid</name>
   <tag></tag>
   <elementGuidId>c3614ed7-f8f0-469c-9fa4-cb9769e91b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ngFormIndividual&quot;)/fieldset[1]/div[@class=&quot;ft-form-row col2-vf&quot;]/div[@class=&quot;ft-form-input&quot;]/app-place-input[1]/div[@class=&quot;place-input&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;][count(. | //*[@class = 'place-input']) = count(//*[@class = 'place-input'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ngFormIndividual&quot;]/fieldset/div[3]/div[2]/app-place-input/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.place-input > input.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bfb8669-f704-4818-9c77-6c3c8f92cc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c173b1f7-8816-4938-a914-18e9acd76dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>e6e20230-c60c-4a97-8dc7-c84d10383cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Place name, Farm, Parish, Municipality, County, Country</value>
      <webElementGuid>450891cc-1994-414e-b06a-97848a79dd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>place-input</value>
      <webElementGuid>9fc94165-62d1-487a-a6ce-983e44688c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngFormIndividual&quot;)/fieldset[1]/div[@class=&quot;ft-form-row col2-vf&quot;]/div[@class=&quot;ft-form-input&quot;]/app-place-input[1]/div[@class=&quot;place-input&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>d4667848-9079-4bcc-a7f7-d178ccf24f2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>44cca91c-d6ff-469d-a295-abf211bb9d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ngFormIndividual']/fieldset/div[3]/div[2]/app-place-input/div/input</value>
      <webElementGuid>887f30ad-2b4d-4ebd-8776-78472c568dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-place-input/div/input</value>
      <webElementGuid>e68e6339-f5e7-42a4-9eb4-897b3431c76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Place name, Farm, Parish, Municipality, County, Country']</value>
      <webElementGuid>3f4cbe47-027b-47ef-b754-0b96c88ce765</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
