<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>5fca5cf1-cfed-4206-9c4c-7cca92a125db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-dialog/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c95cdce-e1c3-47d7-8082-29c7b41bd455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;translated-ltr&quot;]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;main-wrapper&quot;]/app-dialog[1]/div[1]/div[1]</value>
      <webElementGuid>62b7a8a5-42bd-4630-9378-5c16d1eb0cdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-dialog/div/div</value>
      <webElementGuid>fe1bb64b-ff48-4d42-ad6c-91c410cfb943</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
