<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div</name>
   <tag></tag>
   <elementGuidId>0ed53ace-f66e-4641-aee8-5beef3a1375f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-dialog/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a146e074-c93a-4474-9f7f-dff0cf96b43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;main-wrapper&quot;]/app-dialog[1]/div[1]/div[1]</value>
      <webElementGuid>8255559c-9145-43e6-8e45-d674a39a9e24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-dialog/div/div</value>
      <webElementGuid>e10c6e59-7a26-4644-a3c1-88ace11d2454</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
