<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pasi Administrere familietrrOpprett nyt_d466cb</name>
   <tag></tag>
   <elementGuidId>f8ebeec6-0651-4e92-824b-405875ac5762</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.selected-project</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5883a6b9-03d7-44e1-8b52-d1c23bc4438b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected-project</value>
      <webElementGuid>eb4073a1-672c-4ea1-989c-c805a616ac92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pasi Administrere familietrærOpprett nytt slektstrePasi Tree 1Eranga Familypasi123Yasas Postman3PasiYasasHakoonsupun testpasi treeØystein Haaland sitt familietreKDU FTHello PIGDate Test</value>
      <webElementGuid>ac523d24-b58c-4f78-a457-3b090ad53001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;main-wrapper&quot;]/div[2]/app-dashboard[1]/app-subheader-main[1]/div[@class=&quot;sub-header-container&quot;]/div[@class=&quot;project-breadcrumb-base-container&quot;]/app-family-projects[1]/div[@class=&quot;selected-project&quot;]</value>
      <webElementGuid>2437908a-1d11-4deb-85db-a43d8686ab86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[4]</value>
      <webElementGuid>281c56fe-62e3-486c-a23a-5251fa3a0621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version 10.1.121'])[1]/following::div[5]</value>
      <webElementGuid>c71a2962-31e7-4d67-9c63-204b20ad31f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-family-projects/div</value>
      <webElementGuid>b7bc2f6e-83b0-4b08-ba24-30801b27edc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Pasi Administrere familietrærOpprett nytt slektstrePasi Tree 1Eranga Familypasi123Yasas Postman3PasiYasasHakoonsupun testpasi treeØystein Haaland sitt familietreKDU FTHello PIGDate Test' or . = ' Pasi Administrere familietrærOpprett nytt slektstrePasi Tree 1Eranga Familypasi123Yasas Postman3PasiYasasHakoonsupun testpasi treeØystein Haaland sitt familietreKDU FTHello PIGDate Test')]</value>
      <webElementGuid>55ef52b4-6232-4202-9241-75a2fad084bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
