<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Pasi_arrow down arrow-black</name>
   <tag></tag>
   <elementGuidId>dfd0e3f4-0aca-4b11-8248-45090acf07bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.arrow.down.arrow-black</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d096f882-0063-43e5-ada9-074b3563a458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow down arrow-black</value>
      <webElementGuid>ebe6598b-b76d-43a4-899c-0a33fdd8c8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;main-wrapper&quot;]/div[2]/app-dashboard[1]/app-subheader-main[1]/div[@class=&quot;sub-header-container&quot;]/div[@class=&quot;project-breadcrumb-base-container&quot;]/app-family-projects[1]/div[@class=&quot;selected-project&quot;]/i[@class=&quot;arrow down arrow-black&quot;]</value>
      <webElementGuid>d8dc6353-fb2e-4860-93eb-964c11cdc223</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>89c127b4-1cd4-4099-a93e-833e8f4fa25d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
