<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_WEB_menu-edit-icon-1</name>
   <tag></tag>
   <elementGuidId>d5599300-4128-440c-9476-e400f38e658d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.menu-edit-icon-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-drop-menu/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a177bbf4-3718-4c31-8ea0-36c74308e59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/icons/edit-pen-1.svg</value>
      <webElementGuid>89221033-8162-4d75-a696-57817df66e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-edit-icon-1</value>
      <webElementGuid>8e8dce98-63a3-4dbc-9218-ad0e5ba32238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;main-wrapper&quot;]/div[2]/app-family-project-main[1]/div[@class=&quot;ft-form&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;list-gallery&quot;]/app-family-project-list[1]/div[@class=&quot;list-content&quot;]/div[@class=&quot;list-container&quot;]/div[1]/div[@class=&quot;item&quot;]/div[@class=&quot;item-options&quot;]/app-drop-menu[1]/div[@class=&quot;menu-container&quot;]/div[@class=&quot;menu-edit-icon-wrap&quot;]/img[@class=&quot;menu-edit-icon-1&quot;]</value>
      <webElementGuid>23904077-ba87-41c5-83aa-d67fa6909602</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-drop-menu/div/div/img</value>
      <webElementGuid>9433b32b-158a-4c2c-acfa-2dfd1079ebb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/icons/edit-pen-1.svg']</value>
      <webElementGuid>04532cdc-71d8-4b57-aa0b-ec5b94c5731e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
