<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hjem</name>
   <tag></tag>
   <elementGuidId>5d9f7f96-384e-44fb-a522-2b4e37c99b60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.menu-link.nav-menu-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Hjem')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dc96e189-9b61-4e63-81b6-66c044a79166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-link nav-menu-center</value>
      <webElementGuid>4ad9c311-8c4f-4c31-91ca-710bc98efcc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#0</value>
      <webElementGuid>6c4df01a-9e1c-42bb-b02e-13496925c14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hjem</value>
      <webElementGuid>8420f11d-67c9-4e93-99f7-f854983993af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;main-wrapper&quot;]/div[1]/app-menu-main[1]/div[@class=&quot;main-header-container&quot;]/div[@class=&quot;right-menu-container&quot;]/nav[@class=&quot;nav-container&quot;]/ol[@class=&quot;main-menu-container&quot;]/li[@class=&quot;nav-menu-item&quot;]/a[@class=&quot;menu-link nav-menu-center&quot;]</value>
      <webElementGuid>e858f99e-02a3-4751-818f-8ce50e760d26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hjem')]</value>
      <webElementGuid>31e7ce3e-6607-4b55-9499-f636ea7f13d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avbryt'])[1]/following::a[1]</value>
      <webElementGuid>f9052397-7964-4d43-b71f-a26ea07bdc3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lagre'])[1]/following::a[1]</value>
      <webElementGuid>ab897350-4184-455a-98db-03e8bb32fd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rapporter'])[1]/preceding::a[1]</value>
      <webElementGuid>41410b8d-386e-405a-9552-503135b434aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rapportpanel'])[1]/preceding::a[2]</value>
      <webElementGuid>7a27b4ac-165f-4d85-81fd-3ef899e66c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hjem']/parent::*</value>
      <webElementGuid>b1915265-4042-4306-855e-ba36092ef132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#0')]</value>
      <webElementGuid>3d61868d-4a6d-477c-90c2-998706aae1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>a8599768-f13c-44cb-89bd-3f8e75ac685c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#0' and (text() = 'Hjem' or . = 'Hjem')]</value>
      <webElementGuid>15af785e-101f-4766-8f92-fbb5f676e6b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
