<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_WEB_menu-edit-icon-1</name>
   <tag></tag>
   <elementGuidId>2095d55f-1631-4f6b-8f6a-ac72dcd1b62b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.menu-edit-icon-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-drop-menu/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>68e0b0ea-7c19-43ac-b13d-cc9ad369d5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/icons/edit-pen-1.svg</value>
      <webElementGuid>0b1cfdc7-546d-4a23-a952-8c1831b7e4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-edit-icon-1</value>
      <webElementGuid>c2cb91af-aa22-4bf0-9577-d71d86bf4b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;main-wrapper&quot;]/div[2]/app-family-project-main[1]/div[@class=&quot;ft-form&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;list-gallery&quot;]/app-family-project-list[1]/div[@class=&quot;list-content&quot;]/div[@class=&quot;list-container&quot;]/div[1]/div[@class=&quot;item&quot;]/div[@class=&quot;item-options&quot;]/app-drop-menu[1]/div[@class=&quot;menu-container&quot;]/div[@class=&quot;menu-edit-icon-wrap&quot;]/img[@class=&quot;menu-edit-icon-1&quot;]</value>
      <webElementGuid>1e3fd7cc-0416-4f80-acb6-b27caaeebfb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-drop-menu/div/div/img</value>
      <webElementGuid>f88a361c-d236-4cb0-ac0e-cd2f479f0faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/icons/edit-pen-1.svg']</value>
      <webElementGuid>016e824b-9217-4a09-a9c3-402dcee9eec1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
