<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sikkerhetskopi</name>
   <tag></tag>
   <elementGuidId>f924712d-259e-4dff-8b91-bd8da52dbd5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='side_nav02']/li[10]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.backup > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fc2ec5ab-01e1-4fb7-bccf-acd44fbb553f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Backup/Backup</value>
      <webElementGuid>6bf396b9-46fd-4c18-8ce0-ce1135edaac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sikkerhetskopi</value>
      <webElementGuid>65fe112d-1676-45f9-97cd-c594c6581a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side_nav02&quot;)/li[@class=&quot;backup&quot;]/a[1]</value>
      <webElementGuid>5fdd12fb-f3f4-4ce1-b159-45db32434ba9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='side_nav02']/li[10]/a</value>
      <webElementGuid>71bc1805-3aab-4efe-a812-3b405b4e058a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sikkerhetskopi')]</value>
      <webElementGuid>c32eabcb-d170-4bbb-aa0e-bee5757eca58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nyheter'])[1]/following::a[1]</value>
      <webElementGuid>bc046865-425a-4b41-932b-986374330d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Embla brukergrupper'])[1]/following::a[2]</value>
      <webElementGuid>5adc4324-0552-495a-83c0-273de594f711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nedlastinger'])[1]/preceding::a[1]</value>
      <webElementGuid>2a3af898-30ab-463a-b571-4f9e26bc540f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='free Space'])[2]/preceding::a[2]</value>
      <webElementGuid>98c85cd9-1af5-4618-ab72-7786350d7ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sikkerhetskopi']/parent::*</value>
      <webElementGuid>41706f19-a813-41da-b0ba-abcf68d72cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Backup/Backup')]</value>
      <webElementGuid>d967b549-6f2d-421f-b0f7-3afa88837230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>00c43950-1a3c-4a67-9c6c-779bbe01743b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Backup/Backup' and (text() = 'Sikkerhetskopi' or . = 'Sikkerhetskopi')]</value>
      <webElementGuid>8c80fa6b-764a-4d93-8d63-38e62fbaa10f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
