<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LAST OPP DIN SIKKERHETSKOPI_uploadFileName</name>
   <tag></tag>
   <elementGuidId>df395ea9-caf2-4d0d-a626-d132ee5f519f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uploadFileName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uploadFileName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7cb32e23-e5e8-42fc-9b5a-840c2f6a534a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadFileName</value>
      <webElementGuid>5402aa28-ec34-49d6-8ced-c7d9bbe37cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadFileName&quot;)</value>
      <webElementGuid>e059a433-df38-4372-b945-84a955f844e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='uploadFileName']</value>
      <webElementGuid>8a14b90b-b3b5-4764-a955-8e9f97b392f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='backupFrm']/div[3]</value>
      <webElementGuid>7a8490aa-4e19-40d7-8431-9fd9c641f6cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]</value>
      <webElementGuid>f23b064c-73ed-4f9d-b9e2-3ad97dad19ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'uploadFileName']</value>
      <webElementGuid>8d4a99ff-9e3d-4fdf-9ff0-57eca1c05835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
