<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClickFarther</name>
   <tag></tag>
   <elementGuidId>e5651ee9-e0d5-46b5-a037-43fb7ab6a1b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;svg-content&quot;]/g/g[66]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;svg-content&quot;]/g/g[66]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;svg-content&quot;]/g/g[66]</value>
      <webElementGuid>6e67fa2e-6d3d-4150-b72c-35457018dbdb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
