<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hva er CVV2_okButton</name>
   <tag></tag>
   <elementGuidId>3b3f16ca-883c-4d6c-8e4d-845c05b3855a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='okButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#okButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb4f6138-352e-478f-a390-a2e4190b2407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>19fee6a5-a307-4e40-a4b1-6f0bd13490e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>okButton</value>
      <webElementGuid>4a6fe317-dd4f-49bf-b375-aaf50ac800f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Betal</value>
      <webElementGuid>dc9fca56-5130-4ee2-9b00-774833bbcb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if (perforing3dsCheck) {window.document.getElementById('okButton').style.display='none';var progressImageObj=document.getElementById('progressImage');if(progressImageObj)progressImageObj.style.display='inline';Check3dsMethod('https://test.epayment.nets.eu/terminal', '68e9a2bcf75f4dc7951831f55cc34a35', 'cardNumber', '', 'month', 'year', '3', 'status_margins','okButton'); return false;};</value>
      <webElementGuid>63513ccf-df76-4d1f-b2a0-d1baa3d28396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>okButton</value>
      <webElementGuid>85c9514a-d773-483b-9ee1-ca8b64ccdc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;okButton&quot;)</value>
      <webElementGuid>6529667f-4805-4fdb-bb01-17f0f422f5ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='okButton']</value>
      <webElementGuid>27a90d20-6547-49f7-b7ed-23d80174f3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toolbarButtons']/input[3]</value>
      <webElementGuid>e2fefe4f-db73-4542-a586-d56b11f7c9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input[3]</value>
      <webElementGuid>f290b325-89a1-4189-b8ac-e42218695e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'okButton' and @id = 'okButton']</value>
      <webElementGuid>9bb2bcc0-8a1e-48cc-a090-f669a3d66ef2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
