<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_010203040506070809101112</name>
   <tag></tag>
   <elementGuidId>74228eb1-ba04-43cb-8b98-a9feaabcacd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='month']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#month</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>225ff3f8-359b-4182-820c-9728d8bfdaf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Visa$month</value>
      <webElementGuid>63bfb9b8-14e5-45bf-9b19-04483afb5b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>461baa17-0ba4-4d71-9e6a-546b50e43935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Month</value>
      <webElementGuid>df746734-df76-475d-9b63-b5f346918ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	01
	02
	03
	04
	05
	06
	07
	08
	09
	10
	11
	12

</value>
      <webElementGuid>ab577bf1-5f64-404e-8540-cbe95a36de59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;month&quot;)</value>
      <webElementGuid>00c71aee-3388-4c6e-bd85-eca122bfa3e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='month']</value>
      <webElementGuid>e73cbf98-1798-46dd-8826-17cb0fd793a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentPadding']/table[2]/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>31206b27-5d20-4f6c-8ccb-8ec7f0c59d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Utløpsdato (mm/åå)'])[1]/following::select[1]</value>
      <webElementGuid>693a07ed-0e92-4deb-8834-5640fd8bfe70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kortnummer'])[1]/following::select[1]</value>
      <webElementGuid>fa68588f-dc7b-4d17-9b7b-50d68ed264de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CVV2'])[1]/preceding::select[2]</value>
      <webElementGuid>e28bcac9-01bc-419b-8441-bbe656097496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a3392ac0-46f9-46ed-a00a-6524d6dd975d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Visa$month' and @id = 'month' and (text() = '
	01
	02
	03
	04
	05
	06
	07
	08
	09
	10
	11
	12

' or . = '
	01
	02
	03
	04
	05
	06
	07
	08
	09
	10
	11
	12

')]</value>
      <webElementGuid>23bf5153-13be-47c3-bd85-99fa74694966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
