<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ferdig</name>
   <tag></tag>
   <elementGuidId>f3fc2304-e812-439a-92a1-688a245d1c2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paymentmsg']/div/div[6]/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cafa1b1c-4faa-400b-8cd9-7c2d58b019cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary submit</value>
      <webElementGuid>2353b878-0624-49c2-ad4d-c61d98987fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ferdig</value>
      <webElementGuid>bf664ee3-a209-4bcb-8bec-c57cd7821620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentmsg&quot;)/div[@class=&quot;container white-bg&quot;]/div[@class=&quot;button-holder&quot;]/button[@class=&quot;btn btn-primary submit&quot;]</value>
      <webElementGuid>e1cc034b-0a3c-41b7-bbcc-31f2ec5b2fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentmsg']/div/div[6]/button[2]</value>
      <webElementGuid>1f82ef42-06e4-4d1a-8d71-55e0391db652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skriv ut'])[1]/following::button[1]</value>
      <webElementGuid>7130ed13-0c43-4261-8b75-a623f5168e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Annet'])[1]/following::button[2]</value>
      <webElementGuid>6d68d90e-693e-41b1-80e3-71e20ffd41e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='~ Org. nummer:988 610 976'])[1]/preceding::button[1]</value>
      <webElementGuid>ebd06d45-f5ff-4161-a2bd-43ff05246421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kjøpsvilkår'])[1]/preceding::button[1]</value>
      <webElementGuid>4f5a4d8b-e262-4b92-ab19-1239e53ef1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ferdig']/parent::*</value>
      <webElementGuid>07f03106-4071-454e-87d7-f4925785bde3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>9dd47b0e-d5a0-4845-bf9c-6e8c8165a99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Ferdig' or . = 'Ferdig')]</value>
      <webElementGuid>5273aea6-d3d1-4bc1-81c0-73f7d6e69f43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
