<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bestill</name>
   <tag></tag>
   <elementGuidId>1b067d07-8bf6-4e87-b8c0-41a8748daf1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='order-confirmation']/div[2]/div/div[2]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.submit.ladda-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1d237d5c-2223-475b-831a-5020d3c9558b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary submit ladda-button</value>
      <webElementGuid>b9d111e0-1b05-4af4-a749-7f9dae689c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style</name>
      <type>Main</type>
      <value>zoom-in</value>
      <webElementGuid>67829d02-03ab-4cf4-93e5-d2556d8d480b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spinner-size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>7d06a798-03c2-4b15-b8d7-18d45dee893b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spinner-color</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>40aec439-9622-4c5c-a247-06f352f376de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spinner-lines</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>c3994f6a-563a-4dcb-a9b3-0a24dd21ddb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a8c6ce55-4363-499d-a63f-a322bab6617a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bestill</value>
      <webElementGuid>d7a15184-82c2-4825-8e42-37a8e444ae76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-confirmation&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;registration-page&quot;]/div[@class=&quot;form-horizontal&quot;]/div[@class=&quot;button-holder&quot;]/button[@class=&quot;btn btn-primary submit ladda-button&quot;]</value>
      <webElementGuid>54650279-2a00-492e-aee5-8b5917c70a73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='order-confirmation']/div[2]/div/div[2]/div[2]/button</value>
      <webElementGuid>72f818b9-24ce-4111-8eb3-e69c3752cb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Faktura i posten'])[1]/following::button[1]</value>
      <webElementGuid>6923baec-98a8-4045-9a1d-5db3a8a417e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Betalingskort'])[1]/following::button[1]</value>
      <webElementGuid>9799bdd5-9108-4380-bf56-315ed3faa7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='~ Org. nummer:988 610 976'])[1]/preceding::button[1]</value>
      <webElementGuid>14906bf0-8555-402e-8580-d68f94a28806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>9073cc50-88e7-4d80-8446-58b4eda1b802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Bestill' or . = 'Bestill')]</value>
      <webElementGuid>d6cf026c-c0fe-48a5-958f-625075a9ebc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
