<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ok</name>
   <tag></tag>
   <elementGuidId>5f007752-7ae7-4087-a2db-5d6be93944cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='confirm payment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.ok-btn.ladda-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf2b7f9a-05ce-488a-87ca-62fd8c363896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ok-btn ladda-button</value>
      <webElementGuid>251834cb-67b8-46e0-a8ae-e0a51984b1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>confirm payment</value>
      <webElementGuid>643147d1-175d-45b0-9cee-a3cf101340c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style</name>
      <type>Main</type>
      <value>contract</value>
      <webElementGuid>3d117a51-04c3-44fd-8b80-dbde2e4f2f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spinner-size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>50f45e84-01f1-42f8-bd90-f06606437dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spinner-color</name>
      <type>Main</type>
      <value>white</value>
      <webElementGuid>434a3c03-2c21-4213-a0db-97cb41b17155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spinner-lines</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>228cf607-6416-4750-a542-a2db2ea9ee08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>98484d99-4a2c-473f-bf7b-c482678075f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>6d455b49-3cbf-4fca-85bb-c13786a1b5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thank-you-msg&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;registration-page&quot;]/div[@class=&quot;form-horizontal&quot;]/div[@class=&quot;content-holder&quot;]/button[@class=&quot;btn btn-primary ok-btn ladda-button&quot;]</value>
      <webElementGuid>c623b0f2-f4d1-485e-9e9c-b158f3026ba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='confirm payment']</value>
      <webElementGuid>19aa93d3-63f2-4db8-a18e-3b7e05f1c9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='thank-you-msg']/div[2]/div/div/div/button</value>
      <webElementGuid>6074408a-f3b1-4031-9c86-c4f694ea702c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasjon'])[1]/following::button[1]</value>
      <webElementGuid>4e0b8e2c-837f-49b9-94d6-f9a0706b7478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='~ Org. nummer:988 610 976'])[1]/preceding::button[1]</value>
      <webElementGuid>18ce6c8a-b9dc-4a1a-b489-028000fb4c21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>3fcad58b-8e15-4ec5-b9d3-c6d8cf706576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Ok' or . = 'Ok')]</value>
      <webElementGuid>dae42882-bad2-44e5-81b5-fd47fde550f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
