<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mellomnavn_middleName</name>
   <tag></tag>
   <elementGuidId>13d1bfe0-76f9-4b00-a2fd-5fcef1a38c36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='middleName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;middleName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c142f5d3-a7f8-40b1-9b67-dbd98cfeeeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b43d09df-55c4-455f-b549-6e2d32cbe38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>middleName</value>
      <webElementGuid>a4dd16c5-44c7-4a43-b678-9760cb089012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3a604890-ffb8-472f-a2c7-8ecd5d91387c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>middleName</value>
      <webElementGuid>9b999ca5-e86f-4246-8765-102039985774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reg-page&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;registration-page&quot;]/form[@class=&quot;form-horizontal ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-4 col-sm-4 field&quot;]/input[@class=&quot;form-control ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>8fd66968-ca8c-49a0-8b33-11bd2b4c8407</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='middleName']</value>
      <webElementGuid>893ef023-dd3c-4b23-ab50-d3ce31ee367d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='reg-page']/div[2]/div/form/div/div[2]/input</value>
      <webElementGuid>66a9a074-9b28-42b1-aa91-29f7b149ee70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>faa7f521-470a-4c3e-b1eb-e01a60071665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'middleName' and @type = 'text']</value>
      <webElementGuid>656fa0f7-6a4f-4490-ad83-5f2f573e7e85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
