<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Navnet til familietreet_ProjectName</name>
   <tag></tag>
   <elementGuidId>ebf5e597-40aa-4aea-a7ee-4f59d812cce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ProjectName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ProjectName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce8bd7d7-5f2f-4a40-8f47-93b8d8f45d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProjectName</value>
      <webElementGuid>8f4959c3-584c-4d8f-b638-647b6b4bc24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb7d7d74-8359-4836-b5f3-701e3f8d0de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>ProjectName</value>
      <webElementGuid>b36cf2c6-a952-4770-8ba1-852357a66b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>61353632-3d5e-43f6-a8d1-f1a81419b73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;main-wrapper&quot;]/app-dialog[1]/div[1]/div[@class=&quot;dialog-container first-dialog active-dialog&quot;]/app-add-new-project-main[1]/div[1]/div[@class=&quot;tab-container app-dark-bg&quot;]/div[@class=&quot;tab-forms app-light-bg&quot;]/app-add-new-family-project[1]/div[@class=&quot;ft-form&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ft-form-row col1-v100&quot;]/div[@class=&quot;ft-form-input&quot;]/input[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]</value>
      <webElementGuid>4c9e26e6-bbe1-4d90-96bf-a29a677388d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ProjectName']</value>
      <webElementGuid>c08e93cf-31ea-46a1-8351-d55d1845a3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a07055bf-34ef-403e-8045-7a89fb72f915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ProjectName' and @type = 'text']</value>
      <webElementGuid>43dbb359-7d19-465d-ae9e-31ac95e0453b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
