<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kjp n</name>
   <tag></tag>
   <elementGuidId>ffd5b6f1-4091-4f01-bad7-f2a01a3b84ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='NorwegianFamilyHistory']/div[2]/div[10]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn_cart3 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f4847594-9ab0-4000-8604-40a53716096c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://shop.dev.embla.no/0/versjon10ogmedlemskap</value>
      <webElementGuid>3e0bd52f-9f66-4a3a-abe1-1ba05c13edc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>ae642367-036d-45d2-83e4-48a88c950b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kjøp nå</value>
      <webElementGuid>ac635189-830e-40b2-a785-2be971a9942d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NorwegianFamilyHistory&quot;)/div[@class=&quot;body_txt width_640&quot;]/div[@class=&quot;width_640&quot;]/div[@class=&quot;btn_cart3&quot;]/a[1]</value>
      <webElementGuid>88690c16-73ff-4950-b19f-6e8ebc62983c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='NorwegianFamilyHistory']/div[2]/div[10]/div/a</value>
      <webElementGuid>55a5a7b1-69a7-4c67-a443-7d0e9fe6e803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Kjøp nå')])[2]</value>
      <webElementGuid>621aadd3-9f31-41ad-a834-7ae8d469cd8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='sign'])[1]/following::a[1]</value>
      <webElementGuid>31947d52-66c7-4328-ad3f-3cc9be2df211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='free Space'])[3]/preceding::a[1]</value>
      <webElementGuid>257ec3e7-9ba8-4fdd-b98c-ec5767b55eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://shop.dev.embla.no/0/versjon10ogmedlemskap')]</value>
      <webElementGuid>ff5ea523-2dcb-4171-9e88-05c34f19c154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/a</value>
      <webElementGuid>5f9eb267-747e-4c49-9d1f-bc722ba0ff60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://shop.dev.embla.no/0/versjon10ogmedlemskap' and (text() = 'Kjøp nå' or . = 'Kjøp nå')]</value>
      <webElementGuid>3bbf06eb-9c7d-4005-92aa-c80b93638161</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
