<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Medlemskap</name>
   <tag></tag>
   <elementGuidId>e4772094-0a57-45d7-abbb-24ef14d19dc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='navi']/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e68641d9-6f1e-4875-a530-ec6af861515c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Content/NorwegianFamilyHistory</value>
      <webElementGuid>d559a5c5-c6d4-4686-8813-d938f649ed68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Medlemskap</value>
      <webElementGuid>b6109485-108e-42f3-ac7e-aa59a62ba161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navi&quot;)/li[2]/a[1]</value>
      <webElementGuid>9611c9b3-7b68-4f73-a247-9cb9d97570e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='navi']/li[2]/a</value>
      <webElementGuid>61680ccf-e329-4189-97e1-7d69885966de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Medlemskap')]</value>
      <webElementGuid>332e8d0f-52dc-4187-a0bb-ca8f9796b039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hjem'])[1]/following::a[1]</value>
      <webElementGuid>da117202-ccea-4813-914e-4186df67ce25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nytt medlem'])[1]/following::a[2]</value>
      <webElementGuid>c2cc9b0f-a3d7-4e50-8f6d-14f683c71ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nyhetsarkiv'])[1]/preceding::a[1]</value>
      <webElementGuid>8144ed33-a2ea-4dd2-8ce5-ac3d6811ff87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontakt'])[1]/preceding::a[2]</value>
      <webElementGuid>af16e7ed-5e6d-47c9-8490-6ee6c008f1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Medlemskap']/parent::*</value>
      <webElementGuid>1711b3ee-c646-4dbd-a9ef-d15f879c32ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Content/NorwegianFamilyHistory')]</value>
      <webElementGuid>43e881c4-37b1-4938-9405-9bc0c1804627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>028c450b-ac64-4fc8-ab10-9c04f7a98df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Content/NorwegianFamilyHistory' and (text() = 'Medlemskap' or . = 'Medlemskap')]</value>
      <webElementGuid>c1f31281-450f-463d-bad5-521e08eeef1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
