<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg__editor-family-icon</name>
   <tag></tag>
   <elementGuidId>93ac24ad-b739-4d96-a242-7fdec4a2f06a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/div/div[2]/app-dashboard/app-subheader-main/div/app-editors/div/div[3][count(. | //*[@class = 'editor-family-icon']) = count(//*[@class = 'editor-family-icon'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.editor-family-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>21ab0267-dd45-435d-a20d-d9e82a38efd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editor-family-icon</value>
      <webElementGuid>fa224bbd-023b-4de4-9929-4c308d356020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 20 20</value>
      <webElementGuid>3789c4fa-b1c3-441f-b8dd-89af24f97561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/div/div[2]/app-dashboard/app-subheader-main/div/app-editors/div/div[3]</value>
      <webElementGuid>708eaa5a-16d8-4d8d-98bb-52c0bd16736f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
