<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lagre</name>
   <tag></tag>
   <elementGuidId>62f9d085-816a-42dd-9ded-f33d8334378e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Det finnes ingen mediafiler'])[1]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ft-btn.ft-btn-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ec79f67-f3ae-4e33-9487-16c319e87f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-btn ft-btn-active</value>
      <webElementGuid>2ae38ffc-d8cb-45ff-b09b-71730f22c470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>ft-btn </value>
      <webElementGuid>3408a167-1744-4408-9a7c-468a518b2af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>79cea276-a036-4466-8f6c-ee7933a0dbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lagre</value>
      <webElementGuid>bd6c3711-8944-4f2a-b1e4-856c1177be36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;main-wrapper&quot;]/div[2]/app-editor[1]/div[@class=&quot;base-content-wrapper&quot;]/div[@class=&quot;main-content-wrapper&quot;]/app-family-editor-main[1]/div[@class=&quot;content-wrapper-col2-vf&quot;]/div[1]/div[@class=&quot;col-wrap-v&quot;]/app-family-editor[1]/div[@class=&quot;ft-form&quot;]/div[@class=&quot;footer&quot;]/button[@class=&quot;ft-btn ft-btn-active&quot;]</value>
      <webElementGuid>aa941b92-8bfe-464e-90f8-babc417a396d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Det finnes ingen mediafiler'])[1]/following::button[1]</value>
      <webElementGuid>85e79d6d-1510-44a1-a014-7189cd21de3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legg til media'])[1]/following::button[1]</value>
      <webElementGuid>245bb1e7-9e21-445a-8354-6b9ecc5846ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avbryt'])[3]/preceding::button[1]</value>
      <webElementGuid>1be7d8cf-13ee-4738-b3dd-7dac8f4401d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hendelse'])[1]/preceding::button[2]</value>
      <webElementGuid>716d9334-f1cc-460e-9f2b-05df635721a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lagre']/parent::*</value>
      <webElementGuid>80f5edcf-40a9-4403-b1b8-2ffb134f287c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>26833ead-b050-4574-8b01-f8dd52abcb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Lagre' or . = 'Lagre')]</value>
      <webElementGuid>f5636b55-e62a-4bbf-84f2-dfd6719aa413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
