<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_PasiFarther_menu-edit-icon-0</name>
   <tag></tag>
   <elementGuidId>7088cf37-fa61-46da-a020-5000c38bda7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='familyViewModel']/fieldset/div/div[2]/div/div/div[3]/app-drop-menu/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.menu-edit-icon-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3f6daa70-b283-4fe3-9ad6-9225f7285b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/icons/edit-pen-0.svg</value>
      <webElementGuid>92647c68-094f-42ca-98f1-3f632699807c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-edit-icon-0</value>
      <webElementGuid>0464fda9-1164-4bc2-8bd3-a2b925de1558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;familyViewModel&quot;)/fieldset[1]/div[@class=&quot;ft-form-row col2-vf&quot;]/div[@class=&quot;center&quot;]/div[@class=&quot;family-parent-warp&quot;]/div[@class=&quot;family-individual-wrap&quot;]/div[@class=&quot;family-individual-menu-wrap&quot;]/app-drop-menu[1]/div[@class=&quot;menu-container&quot;]/div[@class=&quot;menu-edit-icon-wrap&quot;]/img[@class=&quot;menu-edit-icon-0&quot;]</value>
      <webElementGuid>9c6599c2-2acc-4a81-83cc-a880cf5eb184</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='familyViewModel']/fieldset/div/div[2]/div/div/div[3]/app-drop-menu/div/div/img</value>
      <webElementGuid>b35ac54d-5078-487f-8037-3a1323288576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/app-drop-menu/div/div/img</value>
      <webElementGuid>d304db79-722f-4564-9ff4-d626c33e89ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/icons/edit-pen-0.svg']</value>
      <webElementGuid>bbde9440-f5b1-45f2-83af-0d78fba4b79f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
