<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>use</name>
   <tag></tag>
   <elementGuidId>9ab42974-9c4e-4841-adda-85dd2b8c2285</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/div[2]/app-report/div/div[2]/app-maintreeeditorview/div/div/div/div/app-treeeditorview/div/div/div/div/div/svg/g/g[66]/use</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>use</value>
      <webElementGuid>b454595e-db87-4f92-9350-43002097d0c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>c9ad8c0b-c006-4c07-9aaa-f94e5de5a619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>180</value>
      <webElementGuid>c5385541-17b4-4b95-9da8-0615c4d2d036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xlink:href</name>
      <type>Main</type>
      <value>#1</value>
      <webElementGuid>6c83bf09-07db-4a02-b96e-c7abbea5522c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/div/div[2]/app-report/div/div[2]/app-maintreeeditorview/div/div/div/div/app-treeeditorview/div/div/div/div/div/svg/g/g[66]/use</value>
      <webElementGuid>b10883a0-56a5-4f07-8191-6adee8793426</webElementGuid>
   </webElementProperties>
</WebElementEntity>
