<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_File to uploadNotes about the file to_b892c2</name>
   <tag></tag>
   <elementGuidId>56f585ac-c1e8-4bc5-93e6-cfbb84c837c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;note&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='note']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c5188e4-dcb5-4cd2-8293-58d5bd4ebaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36042a52-8397-4b9b-be82-55419fd2f3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>note</value>
      <webElementGuid>a4d57ab2-a131-4591-a681-31afc5a90cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/input[2]</value>
      <webElementGuid>3fff205f-9e08-44a2-801c-773e6a3f70cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='note']</value>
      <webElementGuid>b3f5ddfd-16a2-46e8-96c9-2f74b0b41825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>76270bc1-daeb-44d0-a8e0-851f5f6205d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'note']</value>
      <webElementGuid>66dc070e-b368-47f1-a0bd-a0b7c9baebc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
