<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_File to uploadNotes about the file to_4f2f05</name>
   <tag></tag>
   <elementGuidId>b2682070-2f48-4584-b860-f0c40e8ae1e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;upfile&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='upfile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c43967e-b8bb-4fe5-895d-0bd1a53b6323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>63bad7db-5bf2-43f5-ac95-9c6df885167e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>upfile</value>
      <webElementGuid>fd4e231e-9a8e-4263-8a27-5ddbc3e0ed87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/input[1]</value>
      <webElementGuid>1c4dbdcc-a805-41c0-a0ee-8b4fe55d0fce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='upfile']</value>
      <webElementGuid>a1a3c0b3-0f6a-421d-babd-5f440535240b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>571ac280-fd44-46d2-a6ee-277c0be08fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'upfile']</value>
      <webElementGuid>34f50684-7779-4b50-be61-9526d7de9d95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
