<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_RessurserOversiktPersonFamilieStedsnavns_bc2571</name>
   <tag></tag>
   <elementGuidId>a60a52ce-80d8-47ee-ad44-d70ff4dfc590</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Artistisk tre'])[1]/following::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>29c7f523-3960-42f1-8900-760af2542cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-menu-item</value>
      <webElementGuid>8c3c44aa-de2d-4add-8945-87f5df2e26d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RessurserOversiktPersonFamilieStedsnavnslisteMultimedialistePersonlisteKildeliste</value>
      <webElementGuid>0a0628ef-387b-4416-bce1-06a6617941f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/div/div[1]/app-menu-main/div/div[1]/nav/ol/li[3]</value>
      <webElementGuid>00c5cad7-97b9-43e0-81bc-d532d42d1ca1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Artistisk tre'])[1]/following::li[1]</value>
      <webElementGuid>da982189-62f8-40aa-b32c-5cc05b5e5f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forfedretavle'])[1]/following::li[2]</value>
      <webElementGuid>7f47d554-95fe-4bc2-bc3c-b2895ba66f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>e9c00bd4-83b5-4027-977c-c5d1070fc462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'RessurserOversiktPersonFamilieStedsnavnslisteMultimedialistePersonlisteKildeliste' or . = 'RessurserOversiktPersonFamilieStedsnavnslisteMultimedialistePersonlisteKildeliste')]</value>
      <webElementGuid>f2228089-871a-421b-b36d-31aaec38fbc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
