<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Farens navn_ng-untouched ng-pristine ng-valid</name>
   <tag></tag>
   <elementGuidId>b431bba9-3ac7-4106-843d-ef08089973f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.base-content-wrapper > app-message-dialog > div.base-panel > div.content-panel > div.content-container > app-individual-prompt > div > div.ft-form-row > div.ft-form-input > input.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39b29cd1-6a16-466f-89d5-8a570a4add34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7d5f20c-1702-40a0-8b83-bd0c7556b528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>7282bebd-5c71-4681-8731-068f82b16a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;main-wrapper&quot;]/div[2]/app-report[1]/div[@class=&quot;base-content-wrapper&quot;]/app-message-dialog[1]/div[@class=&quot;base-panel&quot;]/div[@class=&quot;content-panel&quot;]/div[@class=&quot;content-container&quot;]/app-individual-prompt[1]/div[1]/div[@class=&quot;ft-form-row&quot;]/div[@class=&quot;ft-form-input&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>928d01f0-a1c2-453a-a12d-0df2f4ef0111</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[3]</value>
      <webElementGuid>c4275c83-1777-4b70-bc74-a3749145ac5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-report/div/app-message-dialog/div/div[2]/div/app-individual-prompt/div/div[2]/div/input</value>
      <webElementGuid>069009ae-2e9e-4930-ac53-69c716f72ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>7c007b59-a5d9-47dd-8db3-23aa546a03d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
