<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tittel_reportTitle</name>
   <tag></tag>
   <elementGuidId>a5d5a699-5f7c-46e0-86b8-a313325bf5bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reportTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reportTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db5fc1b0-04fe-4b08-8d2d-de6e0a077029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reportTitle</value>
      <webElementGuid>1a6d312f-a097-436e-8282-f4fcd4b5ae11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0dd631d-f740-4b7c-b91f-86ed7d1973ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ee754dd1-b5e8-4f5a-a8a0-714910b50916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b0f7576a-59ee-4c7c-9560-c5ccb5c233fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e8a38343-954b-431a-93a1-b2bf955e7c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportTitle&quot;)</value>
      <webElementGuid>90e4bc84-91eb-4e2f-b564-18732a8999a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reportTitle']</value>
      <webElementGuid>43746f2f-facd-45d3-a1e4-85dfb25259a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c0e7be74-2536-4d77-9256-e8cdacf581f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'reportTitle' and @type = 'text']</value>
      <webElementGuid>5265d7ea-5603-4d33-a465-df105a247bd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
