<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Lagre</name>
   <tag></tag>
   <elementGuidId>14d3c431-7ea9-49c6-8823-86ac97cba502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ft-btn.ft-btn-active</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>644606a0-3ac3-4850-9052-942f967e4350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-btn ft-btn-active</value>
      <webElementGuid>ea37cb8e-5b65-473d-8c51-99ec76be4d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>form</name>
      <type>Main</type>
      <value>ngFormIndividual</value>
      <webElementGuid>9296e3b9-fa18-403f-87f9-75f847721a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f367b0c5-9376-4c1a-bec9-e069205c739e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-klass</name>
      <type>Main</type>
      <value>ft-btn</value>
      <webElementGuid>10f30ab1-c3ec-41fa-8498-27d1fc527c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>53aa1fed-8f6b-4c04-9366-952ac6a5278d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lagre</value>
      <webElementGuid>8c9fee21-6a4b-41ca-858e-26e2d03eb372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;main-wrapper&quot;]/div[2]/app-editor[1]/div[@class=&quot;base-content-wrapper&quot;]/div[@class=&quot;main-content-wrapper&quot;]/app-individual-editor-main[1]/div[@class=&quot;content-wrapper-col2-vf&quot;]/div[1]/div[@class=&quot;col-wrap-v&quot;]/app-individual-editor[1]/div[@class=&quot;ft-form&quot;]/div[@class=&quot;footer&quot;]/button[@class=&quot;ft-btn ft-btn-active&quot;]</value>
      <webElementGuid>13e9a800-c2da-4770-9577-b2c7d0034a4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>9ad544da-bdfa-4ccd-9ac5-fc55b7c19659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Det finnes ingen mediafiler'])[1]/following::button[1]</value>
      <webElementGuid>17bc14fe-e95b-4696-a41f-490aa16a5215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legg til media'])[1]/following::button[1]</value>
      <webElementGuid>a85fc381-9c39-4972-be01-40a9af153c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slett'])[1]/preceding::button[1]</value>
      <webElementGuid>d6e7593b-dd46-4d4e-a8bd-86ac3bca80a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avbryt'])[2]/preceding::button[2]</value>
      <webElementGuid>40935280-b680-4746-8407-f8aa67a466ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lagre']/parent::*</value>
      <webElementGuid>397c66a8-d84f-44b0-bcce-341f8d3ef756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-individual-editor/div/div[2]/button</value>
      <webElementGuid>544f2310-651b-43c1-a854-150db80e23c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@form = 'ngFormIndividual' and @type = 'submit' and (text() = 'Lagre' or . = 'Lagre')]</value>
      <webElementGuid>dba392dd-3868-4fa6-81c6-778ca233654e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
