<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DeadPlace</name>
   <tag></tag>
   <elementGuidId>b50fd5fe-c242-43d2-b92f-e1586a03510b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ngFormIndividual&quot;]/fieldset/div[5]/div[2]/app-place-input/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ngFormIndividual&quot;]/fieldset/div[5]/div[2]/app-place-input/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ngFormIndividual&quot;]/fieldset/div[5]/div[2]/app-place-input/div/input</value>
      <webElementGuid>1d04e3a2-cf9d-4fb6-aa36-63ae0d629f40</webElementGuid>
   </webElementProperties>
</WebElementEntity>
