<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ddssted</name>
   <tag></tag>
   <elementGuidId>c38f14e6-ebcb-4a25-86dc-3a562a0f5170</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='ngFormIndividual']/fieldset/div[5]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f2628f26-1ef1-4e13-940e-398ea5d61724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-form-input</value>
      <webElementGuid>e0d8be07-b308-4c6b-81a3-13640f41dab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dødssted</value>
      <webElementGuid>60a3bb35-446a-4a9f-8791-4d84fe8d7855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngFormIndividual&quot;)/fieldset[1]/div[@class=&quot;ft-form-row col2-vf&quot;]/div[@class=&quot;ft-form-input&quot;]</value>
      <webElementGuid>730c40b7-9608-4b81-8a7a-149bd13bb2db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ngFormIndividual']/fieldset/div[5]/div[2]</value>
      <webElementGuid>5d1c0752-96e3-4687-a375-1a95e49a4f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dødsdato'])[1]/following::div[3]</value>
      <webElementGuid>59a5032e-9a80-4c1c-ae98-ee1140f72b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ukjent'])[2]/following::div[5]</value>
      <webElementGuid>41d12658-b3a3-4250-96a1-1b4c7dee65c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biografi'])[1]/preceding::div[2]</value>
      <webElementGuid>f14fb583-0885-46f4-badd-39b88b934de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]</value>
      <webElementGuid>d0762d86-eb41-4c68-b7af-671e889d9b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Dødssted' or . = 'Dødssted')]</value>
      <webElementGuid>e605641d-e690-44f1-b164-ffb9bcaa00dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
