<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Avdd_livingStatus</name>
   <tag></tag>
   <elementGuidId>13f6bb9c-337c-4832-8386-026a1ad13c44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='livingStatus'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a4869bd-4106-4742-909e-ada69bf4ce2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>livingStatus</value>
      <webElementGuid>21be5e00-024e-4624-9b79-874a0dfe17e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1ba93fe8-18a3-464e-b04b-37a5bbfd7283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngFormIndividual&quot;)/fieldset[1]/div[@class=&quot;ft-form-row col1-v100&quot;]/div[1]/div[@class=&quot;ft-form-input&quot;]/div[1]/div[@class=&quot;input-radio-container&quot;]/input[1]</value>
      <webElementGuid>105b498b-eece-49d6-b35b-fe2d847aa77d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='livingStatus'])[2]</value>
      <webElementGuid>1fafd812-b651-44f9-b21d-ffc4f8df9099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ngFormIndividual']/fieldset/div[4]/div/div/div/div[2]/input</value>
      <webElementGuid>f4bc0bed-795a-4d73-85fd-77bd6e763e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]/input</value>
      <webElementGuid>0949d6b8-4a5d-4f2a-aa25-32daca72cfbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'livingStatus' and @type = 'radio']</value>
      <webElementGuid>36bd5ee1-d78b-4384-b101-106f62f6dde9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
