<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fdselsdato_date</name>
   <tag></tag>
   <elementGuidId>8e768a16-3def-442d-ab68-f0c26361ff21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;date&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f11241c0-0015-4223-92c6-08940890bf1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>date-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f48dec7f-3ef7-4d05-9c31-aff26a784bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>db92af90-56cf-4351-b44d-087a8c205d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>daa0dd7e-e279-4242-a6e4-3dd988980adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>6464de00-c74b-4cad-9f8d-c5881d448f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d9392f8a-c5c3-4c8e-975e-30b13d543b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngFormIndividual&quot;)/fieldset[1]/div[@class=&quot;ft-form-row col2-vf&quot;]/div[@class=&quot;ft-form-input&quot;]/app-date-input-temp[1]/div[@class=&quot;date-input-container&quot;]/input[@class=&quot;date-input ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>524bad0c-bd8e-49b8-bc16-035973dd0585</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='date']</value>
      <webElementGuid>d80d0935-8dbb-4cc2-8d3a-62a776a39709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ngFormIndividual']/fieldset/div[3]/div/app-date-input-temp/div/input</value>
      <webElementGuid>f4b49765-9fb6-4430-8342-c22ca46e2f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-date-input-temp/div/input</value>
      <webElementGuid>54a69bca-0346-4cc8-aa8c-6fbc529e594a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'date' and @type = 'text']</value>
      <webElementGuid>1d77f5a1-7c5a-4299-baed-b78877bf2555</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
