<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Fdested_btn-addPlace</name>
   <tag></tag>
   <elementGuidId>38436a9c-c9fc-4d18-99e8-e488d8c65118</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='ngFormIndividual']/fieldset/div[3]/div[2]/app-place-input/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.btn-addPlace</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3ec72ada-6b59-4f09-b85f-1914e72dc3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-addPlace</value>
      <webElementGuid>eaa8ca63-5612-41d9-a3a3-9c4f9b7dca1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/icons/add.svg</value>
      <webElementGuid>30e57ef6-2594-4cab-9c10-e5b22755c882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ngFormIndividual&quot;)/fieldset[1]/div[@class=&quot;ft-form-row col2-vf&quot;]/div[@class=&quot;ft-form-input&quot;]/app-place-input[1]/div[@class=&quot;place-input&quot;]/img[@class=&quot;btn-addPlace&quot;]</value>
      <webElementGuid>6a9ccfc7-8ee6-41f2-a43c-cdbf27e37e9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ngFormIndividual']/fieldset/div[3]/div[2]/app-place-input/div/img</value>
      <webElementGuid>879712db-de8a-43f4-a243-daea0f6a2f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-place-input/div/img</value>
      <webElementGuid>bc01115c-c0d4-4748-a395-4c8e8b04624d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/icons/add.svg']</value>
      <webElementGuid>ed012e29-971b-44cf-b1e8-cc9ee8939423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
