<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>font_upload</name>
   <tag></tag>
   <elementGuidId>b51c7371-ba7a-4187-ac50-157ef9bbdd69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btnUpload']/div/font/font</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnUpload > div > font > font</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>6db2a2f7-9465-44df-a776-0b07cd6cfb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>upload</value>
      <webElementGuid>6417105d-da65-4372-a410-f5198e0ecb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnUpload&quot;)/div[1]/font[1]/font[1]</value>
      <webElementGuid>7b474e31-842b-4253-a901-e1ae3a9b1a24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='btnUpload']/div/font/font</value>
      <webElementGuid>d904aa59-e831-4e2d-a0cd-f31e8a638ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose File'])[1]/following::font[2]</value>
      <webElementGuid>56c3841e-ce21-48b1-8b2b-5da650c2e533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special_Hello PIG_with_multimedia_20221006.zip'])[1]/following::font[4]</value>
      <webElementGuid>a4b346c2-0b22-474d-94cb-c4229f7a5174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information'])[1]/preceding::font[1]</value>
      <webElementGuid>75a1ddf0-7958-4a35-95df-b46f2aa65128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you want to delete backup?'])[1]/preceding::font[3]</value>
      <webElementGuid>e6ed1ab8-702b-4aca-92a3-2f2ab42c6827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='upload']/parent::*</value>
      <webElementGuid>eeab0e7e-847e-40af-87cc-193652e92896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/font/font</value>
      <webElementGuid>50d201c7-09ce-4bba-8a15-6bf245f37a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//font[(text() = 'upload' or . = 'upload')]</value>
      <webElementGuid>775eb056-c985-4c8b-899f-3dfadad044f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
