<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Legg til multimedia_ft-btn-round-green-base</name>
   <tag></tag>
   <elementGuidId>3772dc94-16f4-4187-bb44-b4fae559106d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/div[2]/app-editor/div/div/app-individual-editor-main/div/div/div[2]/app-events-main/div/div/div[2]/app-event-form/div/div[1]/form/fieldset/div[6]/div[1]/label/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ft-form-row.col2-v50v50 > div.ft-form-input > label.ft-img-label > img.ft-btn-round-green-base</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>274e1296-6b45-447f-972b-a76f6012216a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-btn-round-green-base</value>
      <webElementGuid>c21f633a-66a8-49b6-8f55-fb7be21b10c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>16763e75-fd90-414d-b5f8-92f3f98d9871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/images/icons/add.svg</value>
      <webElementGuid>274552fc-0217-4d22-92fd-364680da767a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>d2e3bbf0-81c2-49fe-8966-8d399a516245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventModel&quot;)/fieldset[1]/div[@class=&quot;ft-form-row col2-v50v50&quot;]/div[@class=&quot;ft-form-input&quot;]/label[@class=&quot;ft-img-label&quot;]/img[@class=&quot;ft-btn-round-green-base&quot;]</value>
      <webElementGuid>ad551fdf-940a-432f-a1ca-45a48c87317d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='eventModel']/fieldset/div[6]/div/label/img</value>
      <webElementGuid>8b775088-a8ab-467c-8dbd-351bcebf5c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/label/img</value>
      <webElementGuid>d343903a-5114-416b-8467-34e3fb23415e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/images/icons/add.svg']</value>
      <webElementGuid>b22bd57a-e812-429e-a6bb-26663c17a55d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
