<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Screenshot 2022-02-22 130451.png_item-image</name>
   <tag></tag>
   <elementGuidId>026e432d-79a8-4e81-a40c-7fb824e6b974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/div/app-dialog/div/div[2]/app-multimedia-main/div/div[2]/div[2]/app-multimedias/div/div[1]/app-media-gallery/div/div/div[1]/div/img[1]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/app-dialog/div/div[2]/app-multimedia-main/div/div[2]/div[2]/app-multimedias/div/div[1]/app-media-gallery/div/div/div[1]/div/img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6abaef66-940d-45c9-beff-eb58e9def552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-image</value>
      <webElementGuid>67540d0c-2d5d-410f-9121-c54090a63697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>c01107dd-ab68-4124-8739-9e0ba792ebb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>http://dev.api.ft.embla.no/api/multimedia/1/0/1/png/file?onlineId=NN0164484&amp;projectId=45230972-8ef2-4c7a-b69f-5b8149f71afc&amp;v=145664</value>
      <webElementGuid>268f392a-3a14-4460-b8e0-110cb831ccef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/div/app-dialog/div/div[2]/app-multimedia-main/div/div[2]/div[2]/app-multimedias/div/div[1]/app-media-gallery/div/div/div[1]/div/img[1]</value>
      <webElementGuid>de34fc6e-d752-4336-a3ee-5634094a986e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'http://dev.api.ft.embla.no/api/multimedia/1/0/1/png/file?onlineId=NN0164484&amp;projectId=45230972-8ef2-4c7a-b69f-5b8149f71afc&amp;v=145664')]</value>
      <webElementGuid>c29273dd-e085-4851-b99d-40239bec9531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>06acadda-c0ac-418d-b2f6-065ba3e2f38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'http://dev.api.ft.embla.no/api/multimedia/1/0/1/png/file?onlineId=NN0164484&amp;projectId=45230972-8ef2-4c7a-b69f-5b8149f71afc&amp;v=145664']</value>
      <webElementGuid>a56aa09b-d7e6-470d-8c1c-f96ed69eefbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
