<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dato_date</name>
   <tag></tag>
   <elementGuidId>d4553b13-cfc9-469c-b246-b2bde4515017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='date'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ft-form-row.col2-vf.event-place-date > div.ft-form-input > app-date-input-temp > div.date-input-container > input[name=&quot;date&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e40fd19f-5a0c-4a47-8e7d-45aa92e9920f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>date-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>876d02da-50c8-407f-92c1-a485f9addbb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>af9db574-d7b5-4d16-8a0a-5cc6f7637385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1049847-5e82-4acc-8f04-a02877ca2041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>41504b10-396c-456f-ba13-a6ce8291efe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-is-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>343ba679-a371-4aff-ad3d-7fe978ce6883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventModel&quot;)/fieldset[1]/div[@class=&quot;ft-form-row col2-vf&quot;]/div[2]/div[@class=&quot;ft-form-row col2-vf event-place-date&quot;]/div[@class=&quot;ft-form-input&quot;]/app-date-input-temp[1]/div[@class=&quot;date-input-container&quot;]/input[@class=&quot;date-input ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>405bdd82-4056-4b1f-9684-bee7c334af7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='date'])[3]</value>
      <webElementGuid>687c897e-ca64-4465-8944-7762842a8461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='eventModel']/fieldset/div[2]/div[2]/div[2]/div/app-date-input-temp/div/input</value>
      <webElementGuid>40b5eee2-f36f-4c22-8d94-061b7bd174c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/app-date-input-temp/div/input</value>
      <webElementGuid>24d3d5dc-b434-40dd-b4ee-cf7a66bf5482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'date' and @type = 'text']</value>
      <webElementGuid>b4115f2e-ecc6-4572-9de1-e744296a39be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
