<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sourceImg</name>
   <tag></tag>
   <elementGuidId>db56f374-18c1-4390-8b55-ff685ece6c62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/div/app-dialog/div/div[3]/app-multimedia-main/div/div[2]/div[2]/app-multimedia-editor/div/div[1]/div[2]/app-media-input/div/div/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/app-dialog/div/div[3]/app-multimedia-main/div/div[2]/div[2]/app-multimedia-editor/div/div[1]/div[2]/app-media-input/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/div/app-dialog/div/div[3]/app-multimedia-main/div/div[2]/div[2]/app-multimedia-editor/div/div[1]/div[2]/app-media-input/div/div/input</value>
      <webElementGuid>83e5fa46-a324-4b9d-9be8-65b92f5eac62</webElementGuid>
   </webElementProperties>
</WebElementEntity>
