<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>source1</name>
   <tag></tag>
   <elementGuidId>678c873e-15e6-4c05-a1bf-5859828d66ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/div/app-dialog/div/div[2]/app-source-main/div/div[2]/div[1]/a[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/app-root/div/app-dialog/div/div[2]/app-source-main/div/div[2]/div[1]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/div/app-dialog/div/div[2]/app-source-main/div/div[2]/div[1]/a[2]</value>
      <webElementGuid>c1cb33f6-dcd1-4e24-a9bd-35db0bb58a2c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
